version: '2.3'
services:
  dev:
    container_name: e-kikai
    image: ubuntu16.04:tensorflow-gpu-py3-15
    runtime: nvidia
    working_dir: /home/yoshida/Programs
    command: bash
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /data:/data
        - /home/yoshida/Programs/:/home/yoshida/Programs
    environment:
        - DISPLAY=unix$DISPLAY
        - TERM=xterm-256color
        - GRANT_SUDO:"yes"
    ports:
        - "5000:5000"
        - "6006:6006"
    ulimits:
        memlock: -1
        stack: 67108864
    shm_size: 1g
    #stdin_open: true
    tty: true
